- name: Check Skype installed
  shell: which skypeforlinux
  register: skype_check
  ignore_errors: True

- name: Install Skype
  shell: |
    wget -O skype.deb "https://repo.skype.com/latest/skypeforlinux-$(echo `getconf LONG_BIT`).deb"
    dpkg --install skype.deb
    rm -rf skype.deb
  when: skype_check.rc == 1

- name: Check Teamviewer installed
  shell: which teamviewer
  register: teamviewer_check
  ignore_errors: True

- name: Install Teamviewer
  shell: |
    wget -O tv.deb https://download.teamviewer.com/download/teamviewer_i386.deb
    dpkg --install tv.deb
    rm -rf tv.deb
  when: teamviewer_check.rc == 1

- name: Check Slack installed
  shell: which slack
  register: slack_check
  ignore_errors: True

- name: Install Slack
  shell: |
    wget -O slack.deb https://downloads.slack-edge.com/linux_releases/slack-desktop-2.8.2-amd64.deb
    dpkg --install slack.deb
    rm -rf slack.deb
  when: slack_check.rc == 1

- name: Install Gitter
  shell: snap install gitter-desktop
