- name: Install build essentials for ubuntu
  apt:
    name: build-essential
    state: present

- name: Intall nano terminal editor
  apt:
    name: nano
    state: present

- name: Install gedit text editor
  apt:
    name: gedit
    state: present

- name: Install vlc media player
  apt:
    name: vlc
    state: present
    
- name: Install vlc browser plugin
  apt:
    name: browser-plugin-vlc
    state: present

- name: Install redshift with gui for blue light management
  apt:
    name: redshift-gtk
    state: present

- name: Install plank for app dock
  apt:
    name: plank
    state: present

- name: Install curl cli
  apt:
    name: curl
    state: present

- name: Install bash completion
  apt:
    name: bash-completion
    state: present

- name: Check Gyazo installed
  shell: which gyazo
  register: gyazo_check
  ignore_errors: True

# instructions taken from gyazo for linux
# https://github.com/gyazo/Gyazo-for-Linux
- name: Install Gyazo
  shell: |
    curl -s https://packagecloud.io/install/repositories/gyazo/gyazo-for-linux/script.deb.sh | sudo os=ubuntu dist=xenial bash
    apt-get install gyazo -y
  when: gyazo_check.rc == 1

- name: Install snapd
  apt:
    name: snapd
    state: present

- name: Install Libreoffice
  shell: snap install libreoffice

- name: Install i3
  apt:
    name: i3
    state: present

- name: Install i3blocks
  apt:
    name: i3blocks
    state: present

- name: Install nitogren
  apt:
    name: nitrogen
    state: present

- name: Install zsh
  apt:
    name: zsh
    state: present

- name: Disable chsh authentication
  lineinfile:
    dest: /etc/pam.d/chsh
    regexp: '.*pam_shells\.so'
    line: 'auth sufficient  pam_shells.so'

- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
  become: False

- name: Re-enable chsh authentication
  lineinfile:
    dest: /etc/pam.d/chsh
    regexp: '.*pam_shells\.so'
    line: 'auth required  pam_shells.so'

- name: Clone dotfiles
  git:
    repo: https://github.com/neetjn/dotfiles.git
    dest: /tmp/dotfiles
    version: master

- name: Copy dotfiles
  shell: |
    chown -R john /tmp/dotfiles/
    cp -r /tmp/dotfiles/* "{{home_directory}}"
    cp -r /tmp/dotfiles/.* "{{home_directory}}"
  ignore_errors: yes

- name: Adding ppa for GetDeb Apps
  shell: |
    wget -q -O - http://archive.getdeb.net/getdeb-archive.key | sudo apt-key add -
    sh -c 'echo "deb http://archive.getdeb.net/ubuntu zesty-getdeb apps" >> /etc/apt/sources.list.d/getdeb.list'
    apt-get update